---
- name: install packages
  import_tasks: nfs_server_DEBIAN.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Create mountable dir
  file:
    path: "{{ nfs_folder }}"
    state: directory
    mode: 777
    owner: root
    group: root
  notify: restart nfs server

- name: copy /etc/exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
  notify: restart nfs server

- name: flush handlers
  meta: flush_handlers
