---
- name: install packages
  import_tasks: nfs_client_DEBIAN.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Create mountable dir
  file:
    path: "{{ nfs_folder }}"
    state: directory
    mode: 777
    owner: root
    group: root

- name: set mountpoints
  mount:
    name: "{{ nfs_folder }}"
    src:
      "{{hostvars[groups['server'][0]]['ansible_default_ipv4']['address']}}\
      :{{ nfs_folder }}"
    fstype: nfs
    dump: 0
    passno: 2
    state: mounted

- name: Ensure mountable dir is accessible to everyone
  file:
    path: "{{ nfs_folder }}"
    state: directory
    mode: 777
    owner: root
    group: root
